{% set name = "fastreg" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastreg-{{ version }}.tar.gz
  sha256: 1ae6c01464ed586435333c8ad5d77ea18e9bad95d7a91d962b58be736f6daa96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - pandas
    - python >=3.7
    - scipy

test:
  imports:
    - fastreg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/fastreg/
  summary: Fast sparse regressions
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - corentinlelannier
